name: pizzahub
description: "Um aplicativo para listar e explorar pizzas, incluindo informações detalhadas sobre ingredientes, tamanhos e comentários de usuários."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flat_list: ^0.1.14
  provider: ^6.0.0
  page_view_dot_indicator: ^2.1.0
  toast: ^0.3.0
  flutter_share: ^2.0.0
  intl: ^0.19.0
  firebase_auth: ^5.3.3
  google_sign_in: ^6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
